name: astronaut
description: explore

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:

  retrofit: 3.0.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  retrofit_generator: 3.0.1+1
  build_runner: 2.1.7
  json_serializable: 6.1.3
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true